baseURL = "https://dreamy-hamster-04ecb3.netlify.app"
languageCode = "en-us"
paginate = 6
theme = "portio"
title = "Portio"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
# [[menu.main]]
# name = "About"
# url = "#about"
# weight = 2
[[menu.main]]
name = "Services"
url = "#service"
weight = 3
# [[menu.main]]
# name = "Work"
# url = "#portfolio"
# weight = 4
[[menu.main]]
name = "Qualifications"
url = "#resume"
weight = 5
# [[menu.main]]
# name = "Skills"
# url = "#skills"
# weight = 6
[[menu.main]]
name = "Media"
url = "#blog"
weight = 7
# [[menu.main]]
# name = "Contact"
# url = "#contact"
# weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "about"
weight = 1
[[menu.sitemap]]
name = "Frequently Ask Question"
url = "#"
weight = 2
[[menu.sitemap]]
name = "Privacy & Policy"
url = "#"
weight = 3
[[menu.sitemap]]
name = "Latest Article"
url = "#"
weight = 4

[params]
blogPageURL = "blog"
contactLink = "contact"
# copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/EC_white.png"
formspreeURL = "YOUR FORMSPREE URL"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/EC_black.png"

[params.address]
address = "Cheyne walk, London, NW4."
email = "citronpysch@gmail.com"
openingHours = "Open from 9am to 5pm (close over the weekend)"
phone = "+(44) 7960 085 010"

# [params.map]
# APIkey = "YOUR GOOGLE MAP API"
# latitude = "23.7783741"
# longitude = "90.3746808"
# pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/"
weight = 2
[[params.social]]
icon = "fa-pinterest-square"
url = "https://www.pinterest.com/"
weight = 3
[[params.social]]
icon = "fa-twitter-square"
url = "https://twitter.com/"
weight = 4
